### ISSUE TITLE
Dromedary case all the things

### ISSUE THREAD

**Issue by mstoltenburg** [ZeitOnline/docs-zappi#7]
Im Moment sind nur diese Komponenten nicht im _dromedary case_. Sollten wir das ändern in `cpElementId` und `cpElementType`?

https://github.com/ZeitOnline/docs-app-api/blob/a99e798a67bb1597b8571c8e107ad2311f458b12/api.yaml#L122
https://github.com/ZeitOnline/docs-app-api/blob/a99e798a67bb1597b8571c8e107ad2311f458b12/api.yaml#L127

Und diese `properties`:

https://github.com/ZeitOnline/docs-app-api/blob/a99e798a67bb1597b8571c8e107ad2311f458b12/api.yaml#L185
https://github.com/ZeitOnline/docs-app-api/blob/a99e798a67bb1597b8571c8e107ad2311f458b12/api.yaml#L231

Vielleicht wollen wir mal grundsätzlich festlegen, welche Schreibweise wo gewünscht ist. `subMenu`, `cpItem`, `dateFirstPublished` etc. sind hier z.B. schon _dromedary case_. Ich wäre für  _dromedary case_, das dominiert bisher.

**Comment by mstoltenburg** [comment]
Arbeitshypothese nach Diskussion mit @wosc: 

- Ein Styleguide fürs YAML wäre schön.
- Schreibweise: "Objekte" wie CenterpageModuleTeaser bleiben Pascal case, "String-Typen" wie (`uuid` oder `cp_element_id`) und properties benutzen snake case (underscore). Einheitlich wäre halt schön. Das hieße, dass wir z.B. `dateLastPublishedSemantic` oder `subMenu` noch mal umbenennen wollen würden.
- Wir kennen die Meinung/Präferenz von Prepublic nicht.
- Welcher Regel man am Ende folgt ist nicht so wichtig wie das es überhaupt eine Regel gibt.
- Einrückung bei Listen ist noch ein Thema (garnicht, 1 Space, 2 Space … bisher alles dabei)

**Comment by mstoltenburg** [comment]
Siehe #11

**Comment by tomster** [comment]
FWIW: +1 fuer dromedary + snake und 2space indent.
aber hauptsache wir einigen uns auf irgendwas und ziehen das dann glatt.
was prepublic betrifft wuerde ich sagen, die richten sich da nach uns (haetten wir als pyfi damals auch nicht anders gemacht). da noch eine extraschleife zu drehen waere premature optimization IMHO.

**Comment by tomster** [comment]
p.s. bisher hatten wir noch nie issues in unseren projekten benutzt... aber warum eigentlich nicht?
